---
# tasks file for jboss_webserver

  - name: Install - Copy Jboss Webserver from controller
    include_tasks: copy_from_controller.yml
    when: transfer_method == 'csp-to-host' and jboss_amq_exists.stat.exists == False
  
  - name: Install - Download Jboss Webserver from RHN
    include_tasks: rhn_url.yml
    when: transfer_method == 'csp-to-host' and jboss_amq_exists.stat.exists == false
  
  - name: Install - 
    include_tasks: install.yml


